name: Notifications

on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual trigger'

jobs:
  fetchDataAndRunAI:
    env:
      TEAM_ID: 440900
      REMOTE_BRANCH: master
      GMAIL_SENDER: ${{ secrets.GMAIL_SENDER }}
      GMAIL_RECEIVER: ${{ secrets.GMAIL_RECEIVER }}
      GMAIL_PASS: ${{ secrets.GMAIL_PASS }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'

      - name: Install PIP packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the App
        run: |
          cd src
          python scraper.py ${TEAM_ID}
          python data_cleaner.py
          python data_maker.py
          python ai.py
